# Add new issues to the correct project
name: 'Internal: Assign Issue to Project'

on:
  workflow_dispatch:
  issues:
    types:
      - opened

env:
  GITHUB_TOKEN: ${{ github.token }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  add-to-project:
    name: Add Issues to Projects
    runs-on: ubuntu-latest
    steps:
      - name: Add Bug to Bug Board
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: |
          contains(github.event.issue.labels.*.name, 'bug')
        with:
          project: https://github.com/orgs/Azure/projects/194
          column_name: 'Needs triage'
      - name: Add Issues to Backlog Board
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: |
          contains(github.event.issue.labels.*.name, 'enhancement')
        with:
          project: https://github.com/orgs/Azure/projects/363
          column_name: 'Needs triage'
